---
name: Upload an artifact directory to a s3 bucket

inputs:
  application:
    type: string
  s3_bucket:
    type: string
  version:
    type: string
  local_dir:
    type: string

runs:
  using: "composite"
  steps:
    - name: Upload build output
      run: |
        aws s3 sync ${{ inputs.local_dir }} s3://${{ inputs.s3_bucket }}/${{ inputs.application }}/${{ inputs.version }} --only-show-errors
      shell: bash
