---
name: Upload an artifact directory to a s3 bucket

inputs:
  application:
    type: string
  s3_bucket:
    type: string
  version:
    type: string
  local_dir:
    type: string

runs:
  using: "composite"
  steps:
    - name: Upload build output
      run: |
        tar czvf artifact.tar.gz ${{ inputs.local_dir }}
        aws s3 cp artifact.tar.gz s3://${{ inputs.s3_bucket }}/${{ inputs.application }}/${{ inputs.version }}/artifact.tar.gz
        rm artifact.tar.gz
      shell: bash
