---
name: Download a netlify artifact directory

inputs:
  application:
    type: string
  s3_bucket:
    type: string
  version:
    type: string
  local_dir:
    type: string

runs:
  using: "composite"
  steps:
    - name: Download build output
      run: |
        aws s3 sync s3://${{ inputs.s3_bucket }}/netlify/${{ inputs.application }}/${{ inputs.version }} ${{ inputs.local_dir }}
      shell: bash
