---
name: Lookup last deployed version
description: Lookup last deployed version for a given environment from git tags

inputs:
  environment:
    type: string
outputs:
  version:
    value: ${{ steps.lookup_v_tag.outputs.version || steps.lookup_short_sha.outputs.version }}

runs:
  using: "composite"
  steps:
    - name: find v tag
      id: lookup_v_tag
      if: inputs.environment == 'production'
      run: |
        if [[ $(git tag -l "$environment") ]]; then
          last_deployed_version=$(git --no-pager tag --points-at "$environment" | grep '[vx]' | head -n1)
          echo "version=$last_deployed_version" >> "${GITHUB_OUTPUT}"
        fi
      env:
        environment: ${{ inputs.environment }}
      shell: bash

    - name: find
      id: lookup_short_sha
      run: |
        if [[ $(git tag -l "$environment") ]]; then
          last_deployed_version=$(git rev-list -n 1 "$environment" | xargs git rev-parse --short)
          echo "version=$last_deployed_version" >> "${GITHUB_OUTPUT}"
        fi
      env:
        environment: ${{ inputs.environment }}
      shell: bash
