---
name: Update git status check

inputs:
  context:
    type: string
  description:
    type: string
  sha:
    type: string
  status:
    type: string
  token:
    type: string


runs:
  using: "composite"
  run: |
    curl -L \
      -X POST \
      -H "Accept: application/vnd.github+json" \
      -H "Authorization: Bearer $TOKEN" \
      -H "X-GitHub-Api-Version: 2022-11-28" \
      "https://api.github.com/repos/${{ github.repository }}/statuses/$SHA" \
      -d '{"state":"$STATUS","target_url":"${{ github.api_url }}/${{ github.repository }}/runs/${{ github.run_id }}","description":"$DESCRIPTION","context":"$CONTEXT"}'
  env:
    CONTEXT: ${{ inputs.context }}
    DESCRIPTION: ${{ inputs.description }}
    TOKEN: ${{ inputs.token }}
    SHA: ${{ inputs.sha }}
    STATUS: ${{ inputs.status }}
