---
name: "Configure AWS credentials"
description: "Configure AWS credentials for Github Actions using defaults"

inputs:
  aws_account_id:
    type: string
  aws_region:
    type: string
    default: "eu-central-1"
  ci_iam_role:
    type: string
    default: ""

runs:
  using: "composite"
  steps:
    - name: Compute IAM role
      id: ci_identity
      run: |
        if [[ -z "$CI_IAM_ROLE" ]]; then
          echo "iam_role=github-actions-$(echo "$GITHUB_REPOSITORY" | awk -F'/' '{print $2}')" >> ${GITHUB_OUTPUT}
        else
          echo "iam_role=$CI_IAM_ROLE" >> ${GITHUB_OUTPUT}
        fi
      shell: bash

    - name: Configure aws credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-region: ${{ inputs.aws_region }}
        role-to-assume: arn:aws:iam::${{ inputs.aws_account_id }}:role/${{ steps.ci_identity.outputs.iam_role }}
