---
name: "Lint pull request title"

inputs:
  prefixes:
    type: string
    required: true
    description: list of allowed prefix separated by a |

runs:
  using: "composite"
  steps:
    - name: lint pull request title
      run: |
        if ! [[ "$TITLE" =~ (${{ inputs.prefixes }})(\(.+\))?:.+$ ]]; then 
          echo "Invalid pull request title $TITLE"
          echo "Title must use one of the following prefix:  ${{ inputs.prefixes }}"
          echo "Learn more at https://www.conventionalcommits.org/en/v1.0.0/"
          exit 1
        fi
      shell: bash
      env:
        TITLE: ${{ github.event.pull_request.title }}
