---
name: "Lookup git sha"

outputs:
  current:
    value: ${{ steps.git_sha.outputs.current }}
  previous:
    value: ${{ steps.git_sha.outputs.previous }}

runs:
  using: "composite"
  steps:
    - name: Lookup current and previous Git sha
      id: git_sha
      run: |
        REF="$(git rev-parse --short HEAD)"
        PREVIOUS_REF="$(git rev-parse --short HEAD~1)"
        echo "current=$REF" >> "${GITHUB_OUTPUT}"
        echo "previous=$PREVIOUS_REF" >> "${GITHUB_OUTPUT}"
      shell: bash
