---
name: Upload a netlify artifact directory

inputs:
  application:
    type: string
  s3_bucket:
    type: string
  version:
    type: string
  local_dir:
    type: string

runs:
  using: "composite"
  steps:
    - name: Upload build output
      run: |
        aws s3 sync ${{ inputs.local_dir }} s3://${{ inputs.s3_bucket }}/netlify/${{ inputs.application }}/${{ inputs.version }}
      shell: bash
