---
name: "Track deployment time"
description: "Track the deployment time"

inputs:
  environment:
    type: string
    required: true
  application:
    type: string
    required: true
  dd_api_key:
    type: string
    required: true

runs:
  using: "composite"
  steps:
    - name: Track deployment in datadog
      run: |
        set -euo pipefail
        action_run="$(gh api /repos/${{ github.repository }}/actions/runs/${{ github.run_id }})"
        start_ts=$(date -d "$(echo ${action_run} | jq -r .run_started_at)" +"%s")
        now_ts=$(date +%s)
        is_retry=$(if [[ $(echo "${action_run}" | jq '.run_attempt') -gt 1 ]]; then echo "true";else echo "false";fi)
        curl --silent -X POST "https://api.datadoghq.eu/api/v1/distribution_points" \
          -H "Accept: application/json" \
          -H "Content-Type: application/json" \
          -H "DD-API-KEY: ${DD_API_KEY}" \
          -d @- << EOF
            {
              "series": [
                {
                  "metric": "sencrop.ci.deployment_time.dist",
                  "points": [
                    [
                      ${now_ts},
                      [
                        $(( now_ts - start_ts))
                      ]
                    ]
                  ],
                  "tags": [
                    "repository:${{ github.repository }}",
                    "env:$ENV",
                    "environment:$ENV",
                    "application:$APPLICATION",
                    "is_retry:${is_retry}"
                  ]
                }
              ]
            }
        EOF
      shell: bash
      continue-on-error: true
      env:
        DD_API_KEY: ${{ inputs.dd_api_key }}
        ENV: ${{ inputs.environment }}
        GH_TOKEN: ${{ github.token }}
        APPLICATION: ${{ inputs.application }}
