---
name: "Lookup git tag"

outputs:
  current:
    value: ${{ steps.git_tag.outputs.current }}
  previous:
    value: ${{ steps.git_tag.outputs.previous }}

runs:
  using: "composite"
  steps:
    - name: Lookup current and previous Git tag
      id: git_tag
      run: |
        REF="${GITHUB_REF#refs/tags/}"
        TAGS=$(git --no-pager tag -l 'v*' --sort=-v:refname) 
        PREVIOUS_REF=$(echo "$TAGS" | head -n2 | tail -n1)
        echo "current=$REF" >> "${GITHUB_OUTPUT}"
        echo "previous=$PREVIOUS_REF" >> "${GITHUB_OUTPUT}"
      shell: bash
