---
name: Download a netlify artifact directory

inputs:
  application:
    type: string
  environment:
    type: string
  s3_bucket:
    type: string
  version:
    type: string
  dir:
    type: string
    default: "./build"

runs:
  using: "composite"
  steps:
    - name: Download build output
      run: |
        aws s3 sync s3://${{ inputs.s3_bucket }}/netlify/${{ inputs.application }}/${{ inputs.environment }}/${{ inputs.version }} ${{ inputs.dir }}
      shell: bash
