---
name: "Track deployment"
description: "Track a deployment in progress"

inputs:
  current_version:
    type: string
    required: true
  dd_api_key:
    type: string
    required: true
  deployed_version:
    type: string
    required: true
  environment:
    type: string
    required: true
  service:
    type: string
    required: true
  slack_bot_token:
    type: string
  slack_channel:
    type: string
    default: "deployment-updates-prod"
  slack_notify:
    type: boolean
    default: true

runs:
  using: "composite"
  steps:
    - name: Notify deployment in progress on slack
      uses: slackapi/slack-github-action@v1.24.0
      if: inputs.environment == 'production' && inputs.slack_notify == 'true'
      with:
        channel-id: ${{ inputs.slack_channel }}
        slack-message: ":ship: New deployment of `${{ inputs.service }}` (version `${{ inputs.deployed_version }}`) in progress (<${{ github.server_url }}/${{ github.repository }}/compare/${{ inputs.current_version }}...${{ inputs.deployed_version }}|CHANGELOG>)"
      env:
        SLACK_BOT_TOKEN: ${{ inputs.SLACK_BOT_TOKEN }}

    - name: Send deployment in progresss event to datadog
      run: |
        set -euo pipefail
        curl --silent -X POST "https://api.datadoghq.eu/api/v1/events" \
        -H "Accept: application/json" \
        -H "Content-Type: application/json" \
        -H "DD-API-KEY: ${DD_API_KEY}" \
        -d @- << EOF
        {
          "title": "Deployment in progress on $SERVICE",
          "text": "$MESSAGE",
          "tags": [
            "operation:deployment",
            "repository:${{ github.repository }}",
            "env:$ENV",
            "environment:$ENV",
            "application:$SERVICE",
            "service:$SERVICE"
          ]
        }
        EOF
      shell: bash
      env:
        DD_API_KEY: ${{ inputs.DD_API_KEY }} 
        ENV: ${{ inputs.environment }}
        MESSAGE: ${{ inputs.service }} is being updated from version ${{ inputs.current_version }} to ${{ inputs.deployed_version }} on ${{ inputs.environment }}
        REPOSITORY: ${{ github.repository }}
        SERVICE: ${{ inputs.service }}

    - name: Increment deployment metric in datadog
      run: |
        set -euo pipefail
        action_run="$(gh api /repos/${{ github.repository }}/actions/runs/${{ github.run_id }})"
        start_ts=$(date -d "$(echo ${action_run} | jq -r .run_started_at)" +"%s")
        now_ts=$(date +%s)
        is_retry=$(if [[ $(echo "${action_run}" | jq '.run_attempt') -gt 1 ]]; then echo "true";else echo "false";fi)
        curl --silent -X POST "https://api.datadoghq.eu/api/v2/series" \
          -H "Accept: application/json" \
          -H "Content-Type: application/json" \
          -H "DD-API-KEY: ${DD_API_KEY}" \
          -d @- << EOF
            {
              "series": [
                {
                  "metric": "sencrop.ci.deployment",
                  "type": 1,
                  "points": [
                    {
                      "timestamp": ${now_ts},
                      "value": 1
                    }
                  ],
                  "tags": [
                    "repository:${{ github.repository }}",
                    "env:$ENV",
                    "environment:$ENV",
                    "application:$SERVICE",
                    "service:$SERVICE",
                    "is_retry:${is_retry}"
                  ]
                }
              ]
            }
        EOF
      shell: bash
      env:
        DD_API_KEY: ${{ inputs.DD_API_KEY }}
        ENV: ${{ inputs.environment }}
        REPOSITORY: ${{ github.repository }}
        SERVICE: ${{ inputs.service }}
