---
name: Docker tag

on:
  workflow_call:
    inputs:
      aws_region:
        type: string
        default: "eu-central-1"
      ci_iam_role:
        type: string
        default: ""
      docker_image_name:
        type: string
        required: true
      docker_tag_from:
        type: string
        required: true
      docker_tag_to:
        type: string
        required: true

jobs:
  push:
    runs-on: "ubuntu-latest"
    env:
      AWS_DEFAULT_REGION: ${{ inputs.aws_region }}
    permissions:
      id-token: write
      contents: read
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Configure aws credentials
        uses: sencrop/github-workflows/actions/configure-aws-credentials@master
        with:
          aws_account_id: ${{ vars.AWS_ACCOUNT_ID }}
          aws_region: ${{ inputs.aws_region }}
          ci_iam_role: ${{ inputs.ci_iam_role }}

      - name: Tag image
        run: |
          MANIFEST=$(aws ecr batch-get-image --repository-name ${{ inputs.docker_image_name }} --image-ids imageTag=${{ inputs.docker_tag_from }} --output text --query 'images[].imageManifest')
          aws ecr put-image --repository-name ${{ inputs.docker_image_name }} --image-tag ${{ inputs.docker_tag_to}} --image-manifest "$MANIFEST"
