---
name: Stop a standard ECS application

on:
  workflow_call:
    inputs:
      aws_region:
        type: string
        default: "eu-central-1"
      environment:
        type: string
        required: true
      service:
        type: string
        required: true


jobs:
  stop:
    runs-on: ubuntu-latest
    env:
      AWS_DEFAULT_REGION: ${{ inputs.aws_region }}
    permissions:
      id-token: write
      contents: read
    steps:
      - name: checkout
        uses: actions/checkout@v3

      - name: Configure aws credentials
        uses: sencrop/github-workflows/actions/configure-aws-credentials@master
        with:
          aws_account_id: ${{ vars.AWS_ACCOUNT_ID }}
          aws_region: ${{ inputs.aws_region }}
          ci_iam_role: ${{ inputs.ci_iam_role }}


      - name: Stop ECS service
        run: |
          if [[ $(aws ecs describe-services --services "${{ inputs.service }}" --cluster "main-${{ inputs.environment }}" | jq -r '.services[0].desiredCount') -gt 0 ]]; then
            aws ecs update-service --cluster "main-${{ inputs.environment }}" --service "${{ inputs.service }}" --desired-count "0"
            echo "${{ inputs.service }} has been stopped"
          else
            echo "${{ inputs.service }} is already stopped"
          fi
