---
name: Validate yaml files

on: pull_request
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v3
      - name: lint yaml files
        run: yamllint .github/workflows/
