---
name: Manage releases

on:
  workflow_call:
    inputs:
      runs_on:
        type: string
        default: ubuntu-latest-arm64

    outputs:
      prs_created:
        value: ${{ jobs.release-please.outputs.prs_created }}
      releases_created:
        value: ${{ jobs.release-please.outputs.releases_created }}
      pr:
        value: ${{ jobs.release-please.outputs.pr }}

jobs:
  release-please:
    runs-on: ${{ inputs.runs_on }}
    outputs:
      prs_created: ${{ steps.release_please.outputs.prs_created }}
      releases_created: ${{ steps.release_please.outputs.releases_created }}
      pr: ${{ steps.release_please.outputs.pr }}
    permissions:
      contents: write
      issues: write
      pull-requests: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Get app token
        id: app_token
        uses: sencrop/github-workflows/actions/authenticate-github-app@master
        with:
          credentials: ${{ secrets.SENCROP_BOT_CREDENTIALS_TOKEN }}

      - name: Run release-please
        id: release_please
        uses: googleapis/release-please-action@v4
        with:
          token: ${{ steps.app_token.outputs.token }}
          config-file: release-please-config.json
          manifest-file: .release-please-manifest.json
          target-branch: ${{ github.ref_name }}
