name: Terraform plan

on:
  workflow_call:
    inputs:
      aws_region:
        type: string
        default: "eu-central-1"
      environments:
        type: string
        default: "['preproduction', 'production']"
      self_hosted:
        type: boolean
        default: false
      terraform_version:
        type: string
        required: true
      working_directory:
        type: string
        required: true

jobs:
  plan:
    runs-on: ${{ inputs.self_hosted && fromJSON(format('["self-hosted","{0}"]', matrix.environment)) || 'ubuntu-latest' }}
    defaults:
      run:
        working-directory: ${{ inputs.working_directory }}
    strategy:
      # we want both plans to complete if one fails
      fail-fast: false
      matrix:
        # Array input type is currently not supported https://github.com/community/community/discussions/11692
        environment: ${{ fromJson(inputs.environments) }}
    env:
      AWS_DEFAULT_REGION: ${{ inputs.aws_region }}
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      ENV: ${{ matrix.environment }}
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      TF_WORKSPACE: ${{ matrix.environment }}
      TF_LOG: INFO
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Terraform setup
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: ${{ inputs.terraform_version }}

      - name: Terraform init
        run: terraform init

      - name: Terraform validate
        run: terraform validate

      # inspired by https://blog.testdouble.com/posts/2021-12-07-elevate-your-terraform-workflow-with-github-actions/
      - name: Terraform plan
        id: plan
        continue-on-error: true
        run: |
          terraform plan -var-file=${ENV}.tfvars -input=false -no-color -out=tfplan \
          && terraform show -no-color tfplan | sed 's/\x27/ /g'

      - name: Reformat Plan
        run: |
          echo '${{ steps.plan.outputs.stdout || steps.plan.outputs.stderr }}' \
          | sed -E 's/^([[:space:]]+)([-+])/\2\1/g' > plan.txt

      - name: Put Plan in Env Var
        run: |
          PLAN=$(cat plan.txt)
          echo "PLAN<<EOF" >> $GITHUB_ENV
          echo "$PLAN" >> $GITHUB_ENV
          echo "EOF" >> $GITHUB_ENV

      - uses: actions/github-script@v6
        if: github.event_name == 'pull_request'
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const { data: comments } = await github.rest.issues.listComments({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: context.issue.number,
            })
            const commentTitle = ':potted_plant: \`${{ matrix.environment }}\` terraform plan for \`${{ inputs.working_directory }}\`'
            const botComment = comments.find(comment => {
              return comment.user.type === 'Bot' && comment.body.includes(commentTitle)
            })
            const output = `#### ${commentTitle}
            \`\`\`diff\n
            ${{ env.PLAN }}
            \`\`\`
            `
            // Update a comment if it already exists
            if (botComment) {
              github.rest.issues.updateComment({
                owner: context.repo.owner,
                repo: context.repo.repo,
                comment_id: botComment.id,
                body: output
              })
            } else {
              github.rest.issues.createComment({
                issue_number: context.issue.number,
                owner: context.repo.owner,
                repo: context.repo.repo,
                body: output
              })
            }
