---
name: Terraform apply

on:
  workflow_call:
    inputs:
      aws_region:
        type: string
        default: "eu-central-1"
      environment:
        type: string
        required: true
      extra_args:
        type: string
        default: ""
      self_hosted:
        type: boolean
        default: false
      terraform_version:
        type: string
        required: true
      working_directory:
        type: string
        required: true


jobs:
  apply:
    runs-on: ${{ inputs.self_hosted && fromJSON(format('["self-hosted","{0}"]', inputs.environment)) || 'ubuntu-latest' }}
    defaults:
      run:
        working-directory: ${{ inputs.working_directory }}
    env:
      AWS_DEFAULT_REGION: ${{ inputs.aws_region }}
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      ENV: ${{ inputs.environment }}
      EXTRA_ARGS: ${{ inputs.extra_args }}
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      TF_WORKSPACE: ${{ inputs.environment }}
      TF_LOG: INFO
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Terraform setup
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: ${{ inputs.terraform_version }}

      - name: Terraform init
        run: terraform init

      - name: Terraform validate
        run: terraform validate

      - name: Terraform apply
        run: terraform apply -var-file=${ENV}.tfvars -auto-approve -input=false ${EXTRA_ARGS}
