---
name: Terraform plan for ecs applications

on:
  workflow_call:
    inputs:
      aws_region:
        type: string
        default: "eu-central-1"
      service:
        type: string
        required: true
      environments:
        type: string
        default: "['preproduction', 'production']"
      self_hosted:
        type: boolean
        default: false
      terraform_version:
        type: string
        required: true
      working_directory:
        type: string
        default: "./infra/terraform"
      extra_args:
        type: string
        default: ""

jobs:
  plan:
    runs-on: ${{ inputs.self_hosted && fromJSON(format('["self-hosted","{0}"]', matrix.environment)) || 'ubuntu-latest' }}
    defaults:
      run:
        working-directory: ${{ inputs.working_directory }}
    strategy:
      # we want both plans to complete if one fails
      fail-fast: false
      matrix:
        # Array input type is currently not supported https://github.com/community/community/discussions/11692
        environment: ${{ fromJson(inputs.environments) }}
    env:
      AWS_DEFAULT_REGION: ${{ inputs.aws_region }}
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      SERVICE: ${{ inputs.service }}
      ENV: ${{ matrix.environment }}
      EXTRA_ARGS: ${{ inputs.extra_args }}
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      TF_WORKSPACE: ${{ matrix.environment }}
      TF_LOG: INFO
    steps:
      - name: Checkout
        uses: actions/checkout@v3

        # get the current image tag to avoid displaying in a diff in each PR
        # while this information would be accurate (the task definition is going to change)
        # it will be more efficient to display the diff only when there's a real infstracture change
        # if we display the same message on each PR users will get the habit to ignore it
        # and will likely ignore it the day it really matters
      - name: Get current image tag
        run: |
          REF=$(aws ecs describe-task-definition --task-definition "${SERVICE}-${ENV}" --output json | jq -r '.taskDefinition.containerDefinitions[] | select(.name == "'${SERVICE}'") | .image | split(":")[1]')
          echo ${REF}
          echo "REF=$REF" >> ${GITHUB_ENV}

      - name: Terraform setup
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: ${{ inputs.terraform_version }}

      - name: Terraform init
        run: terraform init

      - name: Terraform validate
        run: terraform validate

      # inspired by https://blog.testdouble.com/posts/2021-12-07-elevate-your-terraform-workflow-with-github-actions/
      - name: Terraform plan
        id: plan
        run: terraform plan -var docker_image_tag=${REF} -var-file=${ENV}.tfvars -input=false -no-color -out=tfplan ${EXTRA_ARGS}

        # 1. remove everything before the plan output
        # 2. remove github actions output
        # 3. move +/- at the beggining of the line to leverage github diff display
      - name: Clean and reformat Plan
        run: |
          if terraform show -no-color tfplan | grep "Terraform will perform the following actions"; then
            terraform show -no-color tfplan |\
            sed '/Terraform will perform the following actions/,$!d' |\
            sed '/^::/d' |\
            sed -E 's/^([[:space:]]+)([-+])/\2\1/g'\ > plan.txt
          else
            echo "No changes. Your infrastructure matches the configuration." > plan.txt
          fi

      - name: Put Plan in Env Var
        run: |
          PLAN=$(cat plan.txt)
          echo "PLAN<<EOF" >> $GITHUB_ENV
          echo "$PLAN" >> $GITHUB_ENV
          echo "EOF" >> $GITHUB_ENV

      - uses: actions/github-script@v6
        if: github.event_name == 'pull_request'
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const { data: comments } = await github.rest.issues.listComments({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: context.issue.number,
            })
            const commentTitle = ':potted_plant: \`${{ matrix.environment }}\` terraform plan for \`${{ inputs.working_directory }}\`'
            const botComment = comments.find(comment => {
              return comment.user.type === 'Bot' && comment.body.includes(commentTitle)
            })
            const output = `#### ${commentTitle}
            \`\`\`diff\n
            ${{ env.PLAN }}
            \`\`\`
            <details>
              <summary> More about this </summary>
              This diff doesn't display the upcoming image version change as the new tag version will be computed after the merge.
            </details>`

            // Update a comment if it already exists
            if (botComment) {
              github.rest.issues.updateComment({
                owner: context.repo.owner,
                repo: context.repo.repo,
                comment_id: botComment.id,
                body: output
              })
            } else {
              github.rest.issues.createComment({
                issue_number: context.issue.number,
                owner: context.repo.owner,
                repo: context.repo.repo,
                body: output
              })
            }
