---
name: Find the version of the current build

on:
  workflow_call:
    inputs:
      use_tags:
        type: boolean
        default: false
        description: if true the version will be extracted from the most recent tag value
    outputs:
      version:
        value: ${{ jobs.version.outputs.version }}

jobs:
  version:
    runs-on: ubuntu-latest
    outputs:
      version: ${{ steps.git_hash.outputs.REF || steps.git_tags.outputs.REF }}
    steps:
      - name: checkout
        uses: actions/checkout@v3

      - name: Get version from git hash
        if: "! inputs.use_tags"
        id: git_hash
        run: |
          REF=$(git rev-parse --short HEAD)
          echo "REF=$REF" >> ${GITHUB_OUTPUT}

      - name: Get version from tags
        if: inputs.use_tags
        id: git_tags
        run: |
          REF=${GITHUB_REF#refs/tags/}
          echo "REF=$REF" >> ${GITHUB_OUTPUT}
