---
name: Find the version of the current build

on:
  workflow_call:
    inputs:
      from:
        type: string
        description: where to lookup the version, value can be sha or tag
        required: true
    outputs:
      version:
        value: ${{ jobs.version.outputs.version }}
      previous_version:
        value: ${{ jobs.version.outputs.previous_version }}

jobs:
  version:
    runs-on: ubuntu-latest
    outputs:
      version: ${{ steps.git_sha.outputs.REF || steps.git_tag.outputs.REF }}
      previous_version: ${{ steps.git_sha.outputs.PREVIOUS_REF || steps.git_tag.outputs.PREVIOUS_REF }}
    steps:
      - name: checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: check from input
        run: |
          [[ "${{ inputs.from }}" == "sha" ]] || [[ "${{ inputs.from }}" = "tag" ]]

      - name: Get version from git sha
        id: git_sha
        if: inputs.from == 'sha'
        uses: sencrop/github-workflows/actions/lookup-git-sha@master

      - name: Get version from git tag
        id: git_tag
        if: inputs.from == 'tag'
        uses: sencrop/github-workflows/actions/lookup-git-tag@master
