---
name: Find the version of the current build

on:
  workflow_call:
    inputs:
      from:
        type: string
        description: where to lookup the version, value can be sha or tag
        required: true
    outputs:
      version:
        value: ${{ jobs.version.outputs.version }}
      previous_version:
        value: ${{ jobs.version.outputs.previous_version }}

jobs:
  version:
    runs-on: ubuntu-latest
    outputs:
      version: ${{ steps.git_hash.outputs.REF || steps.git_tags.outputs.REF }}
      previous_version: ${{ steps.git_hash.outputs.PREVIOUS_REF || steps.git_tags.outputs.PREVIOUS_REF }}
    steps:
      - name: checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: check from input
        run: |
          [[ "${{ inputs.from }}" == "sha" ]] || [[ "${{ inputs.from }}" = "sha" ]]

      - name: Get version from git sha
        if: inputs.from == 'sha'
        id: git_hash
        run: |
          REF="$(git rev-parse --short HEAD)"
          PREVIOUS_REF="$(git rev-parse --short HEAD~1)"
          echo "REF=$REF" >> "${GITHUB_OUTPUT}"
          echo "PREVIOUS_REF=$PREVIOUS_REF" >> "${GITHUB_OUTPUT}"

      - name: Get version from git tag
        if: inputs.from == 'tag'
        id: git_tags
        run: |
          REF="${GITHUB_REF#refs/tags/}"
          PREVIOUS_REF="$(git tag -l 'v*' --sort=-v:refname | head -n2 | tail -n1)"
          echo "REF=$REF" >> "${GITHUB_OUTPUT}"
          echo "PREVIOUS_REF=$PREVIOUS_REF" >> "${GITHUB_OUTPUT}"
